# Generated by Django 4.0.1 on 2022-03-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriados', '0003_alter_episodio_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisor',
            name='reviews_episodios',
            field=models.ManyToManyField(through='seriados.ReviewEpisodio', to='seriados.Episodio'),
        ),
    ]
